name: GitHub Actions Deploy
run-name: ${{ github.actor }} GitHub Actions è‡ªå‹•éƒ¨ç½² ğŸš€
on:
  push: # åªæœ‰ç•¶ tag åç¨±ä»¥ 'ver' é–‹é ­ä»¥åŠåˆ†æ”¯ç‚º 'prod' è§¸ç™¼
    tags:
      - "ver*"
    branches:
      - "prod"
jobs:
  autoDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: åˆå§‹åŒ–å°ˆæ¡ˆ
        run: |
          npm install
      - name: æ‰“åŒ…å°ˆæ¡ˆ
        run: |
          npm run build
      - name: éƒ¨ç½²å°ˆæ¡ˆ
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
          if-no-files-found: error
      - name: å°å‡ºç›®å‰å·¥ä½œç’°å¢ƒçš„è³‡æ–™å¤¾çµæ§‹
        run: |
          ls ${{ github.workspace }}
      - name: æ¨é€æ‰“åŒ…å°ˆæ¡ˆè‡³ gh-pages åˆ†æ”¯
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          PUBLISH_BRANCH: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
      - run: echo "è‡ªå‹•æ‰“åŒ…éƒ¨ç½²çµæœ ${{ job.status }}"
